name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Bump version')  # Add this line

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Poetry and Twine
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install twine  # Make sure twine is installed

    - name: Configure Git user
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Build and publish package to PyPI
      env:
        TWINE_USERNAME: "__token__"
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        rm -rf dist/ build/ *.egg-info
        poetry build
        twine upload dist/* -p $PYPI_API_TOKEN --non-interactive
